env_domain: "s1.today"
base_url: "@format https://api.{this.env_domain}/public/v1"
extension_id: "EXT-0000-1111"
extension_domain: "@format ext.{this.env_domain}"
extension_fqdn: "@jinja {{this.extension_id | lower}}.{{this.extension_domain}}"
