apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
  SERVICE_NAME: {{ .Values.serviceName | quote }}
  MPT_EXTENSION_ID: {{ .Values.extensionId | quote }}
