serviceName: mextmock
image:
  repository: nlpapp0336cre.azurecr.io/gha/mextmock
  pullPolicy: IfNotPresent
 
extensionId: EXT-1234-5678
extensionApiKey: api-key
envDomain: s1.today

replicaCount: 1

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []
